name: 'issue-creator'
description: 'Periodically create GitHub issue'
inputs:
  template-issue:
    description: 'Specify the issue number of the template in the repository. e.g. 1'
    required: true
  close-last-issue:
    description: 'If true, issue-creator closes the previous issue.'
    default: true
  check-before-create-issue:
    description: 'The issue will be created only when the status code of this script is 0.'
    default: "echo 'OK'"
  token:
    default: ${{ github.token }}
  discussion:
    description: 'If true, creates a discussion instead.'
    default: false
  repository:
    description: 'Specify a repository where the issue will be created. e.g. rerost/issue-creator'
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: 'rerost/issue-creator@sha256:a27341a35933d82735fc2e6ec0ac23b159a8b319c18d49cd1396f241d0ee9569' # commit: https://github.com/rerost/issue-creator/pull/108/commits/14fab538950c46f91b81e4e2037e4e2abf5d5f1c
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.template-issue }}
    - ${{ inputs.close-last-issue }}
    - ${{ inputs.check-before-create-issue }}
    - ${{ inputs.token }}
    - ${{ inputs.discussion }}
