name: "Check actions work for issue"
on: workflow_dispatch

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          template-issue: 1
